# Usa una imagen base que contenga un servidor web
FROM nginx:latest

# Copia los archivos de tu aplicación al directorio de trabajo de Nginx
COPY . /usr/share/nginx/html

# Expone el puerto 80 en el que Nginx sirve tu aplicación
EXPOSE 80
